### ISSUE TITLE
Picture recorder return type error

### ISSUE THREAD

**Issue by trueshail** [vemarav/signature#2]
PictureRecorder recorder
The return type 'Future<Image>' isn't a 'Image', as defined by the method 'rendered'

![image](https://user-images.githubusercontent.com/45474067/56682191-0fa4d180-6699-11e9-9016-1f6ce7b20f0f.png)

**Comment by vemarav** [comment]
@luv4ever2shail I have fixed this.
changelog:
https://github.com/vemarav/signature/blob/master/lib/main.dart#L169
https://github.com/vemarav/signature/blob/master/lib/main.dart#L84

**Comment by trueshail** [comment]
Thanks 👍
