### ISSUE TITLE
Is it possible to draw on an image and export as a new one?

### ISSUE THREAD

**Issue by AnsonWooBizCloud** [vemarav/signature#5]
Just like someone else did on Android Native.
https://stackoverflow.com/questions/26209532/draw-on-picture-in-android
Thanks!

**Comment by vemarav** [comment]
> Is it possible to draw on an image and export as a new one?

yes, I think this issue#[28047](https://github.com/flutter/flutter/issues/28047) will help. 
Let me know if that didn't worked
