### ISSUE TITLE
Draw over a Photo

### ISSUE THREAD

**Issue by billymahmood** [vemarav/signature#7]
Hey pal,

This is brilliant work, however my requirements are slightly different, I need to allow the user to draw over a Photo they have taken using the camera. 

I am able to add the photo as a child to `CustomPaint` like this 
```
CustomPaint(
            painter: SignaturePainter(points: _points),
            child: Stack(
              children: <Widget>[
                Image.file(File(widget.imagePath)),
                Container(),
              ],
            ),
          ),
``` 

The issue I am having is, the lines do not get drawn over the photo, they seem to go behind the photo, and my 2nd question is how can I save the photo and the lines the user has drawn as one new image?

Thank you for your help

**Comment by vemarav** [comment]
You need to draw image on canvas, rest will work fine. Head over to stackoverflow for this type of questions.
